services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-balancer
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - 9999:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
  
  api1:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    container_name: api1
    environment:
      - PORT=8001
      - API_ID=1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.55
          memory: "30MB"

  api2:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    container_name: api2
    environment:
      - PORT=8002
      - API_ID=2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.55
          memory: "30MB"    
networks:
  backend:
    driver: bridge
  
  payment-processor:
    external: true